### ISSUE TITLE
IndexOutOfRangeException for this OGG file since v0.10.0-alpha

### ISSUE THREAD

**Issue by bert2** [NVorbis/NVorbis#6]
Since the rewrite with v0.10.0-alpha and up to the most recent version I'm getting `IndexOutOfRangeException`s when trying to read a [specific OGG file](https://github.com/bert2/DtmfDetection/blob/master/test/integration/testdata/very_short_dtmf_tones.ogg). I tried it with the `TestApp` from this repo. This is the stack trace of the exception I'm seeing:

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=NVorbis
  StackTrace:
   at NVorbis.Ogg.PacketProvider.CreatePacket(Int32& pageIndex, Int32& packetIndex, Boolean advance, Int64 granulePos, Boolean isResync, Boolean isContinued, Int32 packetCount, Int32 pageOverhead) in D:\DEV\NVorbis\NVorbis\Ogg\PacketProvider.cs:line 195
   at NVorbis.Ogg.PacketProvider.GetNextPacket(Int32& pageIndex, Int32& packetIndex) in D:\DEV\NVorbis\NVorbis\Ogg\PacketProvider.cs:line 178
   at NVorbis.Ogg.PacketProvider.GetNextPacket() in D:\DEV\NVorbis\NVorbis\Ogg\PacketProvider.cs:line 46
   at NVorbis.StreamDecoder.DecodeNextPacket(Int32& packetStartindex, Int32& packetValidLength, Int32& packetTotalLength, Boolean& isEndOfStream, Nullable`1& samplePosition, Int32& bitsRead, Int32& bitsRemaining, Int32& containerOverheadBits) in D:\DEV\NVorbis\NVorbis\StreamDecoder.cs:line 464
   at NVorbis.StreamDecoder.ReadNextPacket(Int32 bufferedSamples, Nullable`1& samplePosition) in D:\DEV\NVorbis\NVorbis\StreamDecoder.cs:line 414
   at NVorbis.StreamDecoder.Read(Single[] buffer, Int32 offset, Int32 count) in D:\DEV\NVorbis\NVorbis\StreamDecoder.cs:line 346
   at NVorbis.VorbisReader.ReadSamples(Single[] buffer, Int32 offset, Int32 count) in D:\DEV\NVorbis\NVorbis\VorbisReader.cs:line 342
   at TestApp.VorbisWaveStream.Read(Single[] buffer, Int32 offset, Int32 count) in D:\DEV\NVorbis\TestApp\VorbisWaveStream.cs:line 92
   at TestApp.VorbisWaveStream.Read(Byte[] buffer, Int32 offset, Int32 count) in D:\DEV\NVorbis\TestApp\VorbisWaveStream.cs:line 79
   at NAudio.Wave.WaveOutBuffer.OnDone()
   at NAudio.Wave.WaveOutEvent.DoPlayback()
   at NAudio.Wave.WaveOutEvent.PlaybackThread()
```

## Exact repro steps

1. Download the [test file](https://github.com/bert2/DtmfDetection/blob/master/test/integration/testdata/very_short_dtmf_tones.ogg) into the `TestFiles` directory:
```powershell
PS> Invoke-WebRequest https://raw.githubusercontent.com/bert2/DtmfDetection/master/test/integration/testdata/very_short_dtmf_tones.ogg -OutFile .\TestFiles\4test.ogg
```
2. Use the `TestApp` project to play `4test.ogg`.

**Expected:** `TestApp` should exit with success after playing the file.

**Actual:** `TestApp` crashes with the exception shown above.

## Additional notes

The crash happens at the end of the file, so maybe the decoder failed to detect the EOF?

Also, I'm not sure whether my file is corrupted or this is a bug in the implementation. But I'm assuming the latter, because the file works without problems when I'm using v0.9.1 by checking out the tag.

**Comment by bert2** [comment]
I think I found the problem. It looks like the last page of that OGG file contains 0 packets and neither [`PacketProvider.GetNextPacket(ref int pageIndex, ref int packetIndex)`](https://github.com/NVorbis/NVorbis/blob/4eff9a7356b8be0b54dd673918c3acb58d999323/NVorbis/Ogg/PacketProvider.cs#L166) nor [`PacketProvider.CreatePacket(..., int packetCount, ...)`](https://github.com/NVorbis/NVorbis/blob/4eff9a7356b8be0b54dd673918c3acb58d999323/NVorbis/Ogg/PacketProvider.cs#L192) handle this case.

This is the complete page as received by [`PageReader.ParsePageHeader(byte[] pageBuf, int? streamSerial, bool? isResync)`](https://github.com/NVorbis/NVorbis/blob/4eff9a7356b8be0b54dd673918c3acb58d999323/NVorbis/Ogg/PageReader.cs#L27):

```
Immediate Window> pageBuf
{byte[28]}
    [0]: 79
    [1]: 103
    [2]: 103
    [3]: 83
    [4]: 0
    [5]: 4
    [6]: 127
    [7]: 93
    [8]: 8
    [9]: 0
    [10]: 0
    [11]: 0
    [12]: 0
    [13]: 0
    [14]: 106
    [15]: 191
    [16]: 203
    [17]: 22
    [18]: 17
    [19]: 0
    [20]: 0
    [21]: 0
    [22]: 96
    [23]: 189
    [24]: 234
    [25]: 244
    [26]: 1
    [27]: 0
```

I think the last page byte (`pageBuf[27]`) technically is some page data, because the header only uses the first 26 bytes (right?), but I assume it's some kind of terminating 0 byte?

**Comment by bert2** [comment]
Full disclosure: I did a little reading into the OGG format (maybe I should have done this before creating the PR 🙈), and I found out that `pageBuf[26]` tells us that there are `1` segments in the segments table. The table entry for that segment at `pageBuf[27]` in turn tells us that this segment has a size of `0` in the page body.

To be honest I have no clue where that "page body" is located and thus I'm totally unsure if there is a cleaner way to handle such a segment.

**Comment by ioctlLR** [comment]
Wow, that's a fun one...  So the file is actually invalid.  Ogg does support empty pages, but the final page of a Vorbis stream cannot be empty (it must have EOS set and have just the final packet in it).  Adding up the pageBuf[26] bytes following offset 26 should give a positive value, and the final byte cannot be 255.  Following that should be a count of bytes equal to the sum of the previous calculation (pageBuf[26 ... 28] = {2, 255, 21} would have a total page length of 27 + 2 + 276 = 305 bytes).

I'll have to play with this a bit to figure out how to cleanly support the file in question.  Probably the simplest is to make the packet logic skip the page if zero length...  Both readers will need to be updated, though.

**Comment by ioctlLR** [comment]
Check out PR #8 for a possible fix.  It seems to work fine for me.

**Comment by bert2** [comment]
I just tried the fixed master branch and it works fine. Thanks!
